apiVersion: v1
kind: ServiceAccount
metadata:
  name: blueteamapp-sa
  namespace: kube-system


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: blueteamapp-namespace-manager
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "get", "list"]

--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: blueteamapp-namespace-binding
subjects:
  - kind: ServiceAccount
    name: blueteamapp-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: blueteamapp-namespace-manager
  apiGroup: rbac.authorization.k8s.io
