apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windows-pvc-80-server-2022-01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
  storageClassName: thin-disk

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windows-pvc-1-server-2022-02
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: thin-disk

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows-deployment-mod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: windows-app-mod
  template:
    metadata:
      labels:
        app: windows-app-mod
    spec:
      containers:
        - name: windows-container
          image: learningdevops05/kvm-win-server-2022:v4
          volumeMounts:
            - mountPath: /storage
              name: windows-storage-mod
            - mountPath: /oem
              name: windows-oem-mod
            - mountPath: /dev/kvm
              name: dev-kvm-mod
          command: [sh, -c, 'cp -r /mnt/storage/* /storage/ && /usr/bin/tini -s /run/entry.sh']
          securityContext: # Add security context here
            privileged: true
          resources:
            requests:
              cpu: "2"         # Reserve 1 CPU for the container
              memory: "4Gi"     # Reserve 2Gi memory
            limits:
              cpu: "2"            # Allow up to 2 CPU usage
              memory: "5Gi"       # Allow up to 4Gi memory
      volumes:
        - name: windows-storage-mod
          persistentVolumeClaim:
            claimName: windows-pvc-80-server-2022-01 # Ensure the PVC exists in the new namespace
        - name: windows-oem-mod
          persistentVolumeClaim:
            claimName: windows-pvc-1-server-2022-02 # Ensure the PVC exists in the new namespace
        - name: dev-kvm-mod
          hostPath:
            path: /dev/kvm
