apiVersion: v1
kind: Pod
metadata:
  name: blacksky-sandbox-pod
  # namespace: it  # Update or remove based on your setup
  labels:
    app: blacksky-sandbox
spec:
  restartPolicy: Always
  containers:
    - name: blacksky-container
      image: '192.168.1.15:5000/blacksky:latest'
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
        # allowPrivilegeEscalation: true
        # readOnlyRootFilesystem: false
        seccompProfile:
          type: RuntimeDefault
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"
          ephemeral-storage: "5Gi"
        requests:
          cpu: "0.5"
          memory: "256Mi"
          ephemeral-storage: "2Gi"