apiVersion: v1
kind: Pod
metadata:
  name: mal-ware-sandbox-pod
  # namespace: it  # Update or remove based on your setup
  labels:
    app: mal-ware-sandbox
spec:
  restartPolicy: Always
  containers:
    - name: mal-ware-container
      image: '192.168.1.15:5000/malware:v1'
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
        # allowPrivilegeEscalation: true
        # readOnlyRootFilesystem: false
        seccompProfile:
          type: RuntimeDefault
      resources:
        limits:
          cpu: "4"
          memory: "5Gi"
          ephemeral-storage: "50Gi"
        requests:
          cpu: "4"
          memory: "4Gi"
          ephemeral-storage: "50Gi"
      volumeMounts:
        - name: kvm
          mountPath: /dev/kvm
  volumes:
    - name: kvm
      hostPath:
        path: /dev/kvm
        type: CharDevice
