apiVersion: v1
kind: Secret
metadata:
  name: viper-flag
  # namespace: 
type: Opaque
stringData:
  flag: Cyberrange{default-Arzs64iyCBIiKd1jBPPPtC0TwrwLzyCc}
---

apiVersion: v1
kind: Pod
metadata:
  name: viper-challenge
  labels:
    app: challenge
spec:
  restartPolicy: Never
  containers:
    - name: challenge
      image: '192.168.1.15:5000/ctf_viper:latest'
      env:
        - name: FLAG
          valueFrom:
            secretKeyRef:
              name: viper-flag
              key: flag
