apiVersion: v1
kind: Pod
metadata:
  name: nginx-static-ip-pod-team-c-01
  namespace: team-c
  annotations:
    cni.projectcalico.org/ipAddrs: '[ "172.16.3.10" ]'
spec:
  containers:
  - name: nginx-container
    image: nginx
