apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    debug             
        Daemon       Off
        Parsers_File parsers.conf

    [INPUT]
        Name         tail
        Path         /var/log/pods/*/*.log         
        Tag          kube.*
        Parser       cri                           
        Refresh_Interval 5
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [FILTER]
        Name        kubernetes
        Match       kube.*
        Merge_Log   On
        Keep_Log    Off
        Kube_URL    https://kubernetes.default.svc:443
        Kube_CA_File /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix kube.var.log.pods.

    [OUTPUT]
        Name        stdout
        Match       *                          
        Format      json                       
        json_date_key time                     
        json_date_format iso8601               

    [OUTPUT]
        Name        forward
        Match       *
        Host        192.168.3.159              
        Port        1514                       
        tls         On
        tls.verify  Off
  parsers.conf: |
    [PARSER]
        Name        cri
        Format      regex
        Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) F (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%LZ
        Time_Keep   On
