---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m-web-jollyrogers-pod-team-b
  namespace: team-b # Change this to your specific namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m-web-jollyrogers-team-b
  template:
    metadata:
      labels:
        app: m-web-jollyrogers-team-b
    spec:
      containers:
      - name: m-web-jollyrogers-team-b
        image: nomi089/web:m-web-jollyrogers-team-b
        # command: ["/bin/sh", "-c", "apt-get update && apt-get install -y curl iputils-ping && sleep 3600"]
        ports:
        - containerPort: 8001
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "200m"
            memory: "400Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: m-web-jollyrogers-service-team-b
  namespace: team-b # Change this to your specific namespace
spec:
  selector:
    app: m-web-jollyrogers-team-b
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
  type: LoadBalancer
  loadBalancerIP: 172.17.102.14 # Assign a specific external IP
