---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: johnselpeti-oneschool-pod-team-b
  namespace: team-b # Change this to your specific namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: johnselpeti-oneschool-team-b
  template:
    metadata:
      labels:
        app: johnselpeti-oneschool-team-b
    spec:
      containers:
      - name: johnselpeti-oneschool-team-b-container
        image: johnselpeti/oneschool:v1
        # command: ["/bin/sh", "-c", "apt-get update && apt-get install -y curl iputils-ping && sleep 3600"]
        ports:
        - containerPort: 8002
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "200m"
            memory: "400Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ujohnselpeti-oneschool-service-team-b
  namespace: team-b # Change this to your specific namespace
spec:
  selector:
    app: johnselpeti-oneschool-team-b
  ports:
  - protocol: TCP
    port: 8002
    targetPort: 8002
  type: LoadBalancer
  loadBalancerIP: 172.17.102.15 # Assign a specific external IP
