apiVersion: v1
kind: Pod
metadata:
  name: nginx-static-ip-pod-team-b-01
  namespace: team-b
  annotations:
    cni.projectcalico.org/ipAddrs: '[ "172.16.2.10" ]'
spec:
  containers:
  - name: nginx-container
    image: nginx
