apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-tools-team-b-01
  namespace: team-b
spec:
  containers:
  - name: ubuntu-tools
    image: ubuntu:latest
    command: ["sleep", "3600"]  # Keeps the pod running
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
    securityContext:
      capabilities:
        add:
          - NET_ADMIN  # Required for ping
