apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssti-deployment-ctf
  labels:
    app: ssti-ctf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssti-ctf
  template:
    metadata:
      labels:
        app: ssti-ctf
    spec:
      # runtimeClassName: gvisor  # Secure runtime 
      # restartPolicy: Always  # Explicitly set
      containers:
        - name: ssti
          image: abeerfatima/rendermethis:v3
          # securityContext:
          #   # allowPrivilegeEscalation: false  # Prevent privilege escalation attacks
          #   # readOnlyRootFilesystem: true  # Ensures root filesystem is immutable
          #   seccompProfile:
          #     type: RuntimeDefault  # Uses default syscall restrictions
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
              ephemeral-storage: "500Gi"
            requests:
              cpu: "300m"
              memory: "128Mi"
              ephemeral-storage: "250Mi"
