apiVersion: v1
kind: Pod
metadata:
  name: open-school-static-ip-pod-team-n-01
  namespace: team-n
  annotations:
    cni.projectcalico.org/ipAddrs: '[ "172.16.14.11" ]'
spec:
  containers:
  - name: open-school
    image: johnselpeti/oneschool:v1
