apiVersion: v1
kind: Service
metadata:
  name: ubuntu-service
spec:
  selector:
    app: ubuntu
  type: LoadBalancer
  externalTrafficPolicy: Local   # <-- PRESERVE CLIENT IPs
  ports:
  - name: udp-port
    port: 9999
    targetPort: 9999
    protocol: UDP
