apiVersion: v1
kind: Pod
metadata:
  name: hash84-challenge
  namespace: hash84
  labels:
    app: challenge
spec:
  restartPolicy: Never
  containers:
  - name: challenge
    image: ubuntu:20.04
    command: ["/bin/bash", "-c"]
    args:
      - |
        echo "[$(date)] Writing flag..." && \
        echo "$FLAG" > /flag.txt && \
        chmod 400 /flag.txt && \
        echo "Flag set at /flag.txt"; \
        while true; do sleep 3600; done
    env:
    - name: FLAG
      valueFrom:
        secretKeyRef:
          name: challenge-flag
          key: flag
