apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-team-e-01
  namespace: team-e
  labels:
    app: nginx-team-e-01
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-team-e-01
  namespace: team-e
spec:
  selector:
    app: nginx-team-e-01
  type: LoadBalancer
  loadBalancerIP: 172.17.105.11  # Specify the IP address here
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
