apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq-ctf
  labels:
    app: activemq-ctf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activemq-ctf
  template:
    metadata:
      labels:
        app: activemq-ctf
    spec:
      runtimeClassName: gvisor  # Secure runtime 
      restartPolicy: Always  # Explicitly set
      containers:
        - name: activemq
          image: 192.168.3.46:5000/activemq-ctf:v1
          securityContext:
            allowPrivilegeEscalation: false  # Prevent privilege escalation attacks
            readOnlyRootFilesystem: true  # Ensures root filesystem is immutable
            seccompProfile:
              type: RuntimeDefault  # Uses default syscall restrictions
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
              ephemeral-storage: "1Gi"
            requests:
              cpu: "500m"
              memory: "256Mi"
              ephemeral-storage: "500Mi"
