# Cluster-wide permissions for namespaces, configmaps and nodes
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-health-check-cluster-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "get" ,"patch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["list", "get", "patch"]  # Adjust verbs depending on your needs

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-health-check-cluster-binding
subjects:
  - kind: ServiceAccount
    name: node-health-check-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: node-health-check-cluster-role
  apiGroup: rbac.authorization.k8s.io
