# nginx-service-team-a.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: team-a # or prod
spec:
  selector:
    app: nginx-team-a
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000  # You can specify a port within the range 30000-32767
  type: NodePort

