# admission-controller-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: admission-controller-service
  namespace: kube-system
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: admission-controller
  # type: ClusterIP
