# admission-controller-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission-controller
  template:
    metadata:
      labels:
        app: admission-controller
    spec:
      serviceAccountName: admission-controller-sa  # Specify your service account name here
      containers:
        - name: admission-controller
          image: learningdevops05/admission-controller:latest
          ports:
            - containerPort: 443
        volumeMounts:
        - name: certs
          mountPath: "/etc/webhook/certs"
          readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: admission-controller-tls
          # Add any necessary environment variables or volume mounts
