# admission-controller-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission-controller
  template:
    metadata:
      labels:
        app: admission-controller
    spec:
      containers:
        - name: admission-controller
          image: <your-registry>/admission-controller:latest
          ports:
            - containerPort: 443
          # Add any necessary environment variables or volume mounts
