---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission-controller
  template:
    metadata:
      labels:
        app: admission-controller
    spec:
      serviceAccountName: admission-controller-sa
      containers:
        - name: admission-controller
          image: learningdevops05/admission-controller:v1.3
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: certs
          secret:
            secretName: admission-controller-tls
