apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admission-controller-binding
subjects:
- kind: ServiceAccount
  name: admission-controller-sa
  namespace: kube-system  # Make sure this matches the namespace where your service account is located
roleRef:
  kind: ClusterRole
  name: admission-controller-role
  apiGroup: rbac.authorization.k8s.io
