# mutating-webhook-configuration.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: admission-controller-webhook
webhooks:
  - name: admission.controller.svc.com
    clientConfig:
      service:
        name: admission-controller-service
        namespace: default
        path: "/mutate"
      caBundle: <ca-bundel>
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["*"]
        resources: ["namespaces"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
