apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admission-controller-rolebinding
  namespace: default    # Your namesapce here
subjects:
- kind: ServiceAccount
  name: admission-controller-sa
  namespace: default    # Your namesapce here
roleRef:
  kind: Role
  name: admission-controller-role
  apiGroup: rbac.authorization.k8s.io
