apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default       # Your Namespace here
  name: admission-controller-role
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
