# validating-webhook-configuration.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: admission-controller-webhook
webhooks:
  - name: admission.controller.svc.com
    clientConfig:
      service:
        name: admission-controller-service
        namespace: default
        path: "/validate"
      caBundle: <ca-bundel>
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["*"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
