# validating-webhook-configuration.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: admission-controller-webhook
webhooks:
  - name: admission-controller.kube-system.svc
    clientConfig:
      service:
        name: admission-controller
        namespace: kube-system
        path: "/admission"
      caBundle: <ca-bundel>
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["namespaces"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
