apiVersion: apps/v1
kind: Deployment
metadata:
  name: struts-ctf
  labels:
    app: struts-ctf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: struts-ctf
  template:
    metadata:
      labels:
        app: struts-ctf
    spec:
      runtimeClassName: gvisor  # Secure runtime 
      # restartPolicy: Always  # Explicitly set
      containers:
        - name: struts
          image: abeerfatima/struts-ctf
          securityContext:
            # allowPrivilegeEscalation: false  # Prevent privilege escalation attacks
            # readOnlyRootFilesystem: true  # Ensures root filesystem is immutable
            seccompProfile:
              type: RuntimeDefault  # Uses default syscall restrictions
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
              ephemeral-storage: "1Gi"
            requests:
              cpu: "500m"
              memory: "256Mi"
              ephemeral-storage: "500Mi"
