# Create Namespce 
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: metallb-system
# Namespace is already cready using the installation script so 
# no need to create it again.
# ---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.3.30-192.168.3.49

---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: team-a-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.17.101.10-172.17.101.50

---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: team-b-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.17.102.10-172.17.102.50
