apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-pool-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - default-pool

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: team-a-pool-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - team-a-pool

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: team-b-pool-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - team-b-pool
