apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-alert-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""  # Ensure storageClassName is empty if you're manually managing PVs
