apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  annotations:
	  volume.beta.kubernetes.io/storage-class: thin-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: thin-disk
