apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-alert-pv-1
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  vsphereVolume:
    volumePath: "[datastore1] pv-02-01.vmdk"
    fsType: ext4
