apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vsphere-block-storage
provisioner: csi.vsphere.vmware.com
parameters:
  datastore: "datastore1"
  diskformat: "thin"
  # storagepolicyname: "your-storage-policy"   # Optional
reclaimPolicy: Retain
volumeBindingMode: Immediate
