apiVersion: v1
kind: Secret
metadata:
  name: vsphere-config-secret
  namespace: vmware-system-csi
data:
  user: Ymx1ZXRlYW1hcHA=
  password: QWRtaW5AY3RmMUA=
  vc_ip: MTkyLjE2OC4zLjIxNw==  # vCenter IP
  datacenter: RGVsbFNlcnZlcl8wMQ==
