apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: thin-disk-ds252
provisioner: csi.vsphere.vmware.com
parameters:
  datastore: DataStore2-252
reclaimPolicy: Delete

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: thin-disk-ds253
provisioner: csi.vsphere.vmware.com
parameters:
  datastore: DataStore2-253
reclaimPolicy: Delete
